import React from 'react';
import './AboutFruit.css'; // Import external CSS file

const fruitsData = [
    {
      name: "Apple",
      region: "Worldwide",
      uses: "Eating raw, cooking, juice",
      marketValue: "$3 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9wsG-68QfkOkIR7Ysa_CFmpjBx1LbksAx1g&s",
      fallbackText: "Apple - A popular fruit known for its crisp taste and versatility.",
    },
    {
      name: "Banana",
      region: "Tropics",
      uses: "Eating raw, baking, smoothies",
      marketValue: "$1 per bunch",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnyEUsHKHb42TRKcFNxenSI9vpUHi0ZMhD_g&s",
      fallbackText: "Banana - A sweet and soft fruit commonly used in baking and smoothies.",
    },
    {
      name: "Orange",
      region: "Subtropics",
      uses: "Juice, eating raw",
      marketValue: "$2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTq779novU3KONBe9aIfxT3xiPXaNf8Pslfw&s",
      fallbackText: "Orange - Citrus fruit known for its juicy sweetness and high vitamin C content.",
    },
    {
      name: "Strawberry",
      region: "Worldwide",
      uses: "Desserts, smoothies, eating raw",
      marketValue: "$4 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ72-X4vyUN3h1pu1Z9j9aoFSxS98cRwgFIpw&s",
      fallbackText: "Strawberry - A sweet, red fruit used in desserts and smoothies.",
    },
    {
      name: "Grapes",
      region: "Worldwide",
      uses: "Wine, eating raw, juice",
      marketValue: "$3 per pound",
      image: "https://images.indianexpress.com/2021/02/grapes-1200.jpg",
      fallbackText: "Grapes - Juicy fruit used for eating, juice, and wine production.",
    },
    {
      name: "Watermelon",
      region: "Tropics, subtropics",
      uses: "Eating raw, juice",
      marketValue: "$0.5 per pound",
      image: "https://www.thespruceeats.com/thmb/BDlv0gfycFbWNKpZHFY6LO6JM30=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-127741243-5892285b3df78caebc8da2e8.jpg",
      fallbackText: "Watermelon - Refreshing fruit perfect for hot weather, enjoyed raw or as juice.",
    },
    {
      name: "Pineapple",
      region: "Tropics",
      uses: "Eating raw, juice, cooking",
      marketValue: "$2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHCebcn-XCvFFmVnX5hAUhTht_uiDzjPDeVg&s",
      fallbackText: "Pineapple - Tangy fruit used in cooking, juices, and desserts.",
    },
    {
      name: "Mango",
      region: "Tropics, subtropics",
      uses: "Eating raw, juice, desserts",
      marketValue: "$1.5 per pound",
      image: "https://plantparadise.in/cdn/shop/products/Background-hd-Mango-Wallpaper-Download_90144dd9-3d28-4186-a105-85ad7846a7f2.jpg?v=1691200169",
      fallbackText: "Mango - Sweet fruit enjoyed raw, in juices, or as part of desserts.",
    },
    {
      name: "Peach",
      region: "Temperate regions",
      uses: "Eating raw, desserts, cooking",
      marketValue: "$3 per pound",
      image: "https://5.imimg.com/data5/SELLER/Default/2023/9/340781037/XT/KA/ZP/189247658/peach-500x500.jpg",
      fallbackText: "Peach - Juicy fruit used in cooking and desserts, known for its sweet flavor.",
    },
    {
      name: "Pomegranate",
      region: "Middle East, Asia",
      uses: "Juice, eating raw",
      marketValue: "$4 per pound",
      image: "https://blog-images-1.pharmeasy.in/blog/production/wp-content/uploads/2022/05/10162555/5-6.jpg",
      fallbackText: "Pomegranate - Fruit known for its tart seeds and juice.",
    },
    {
      name: "Kiwi",
      region: "New Zealand, China",
      uses: "Eating raw, desserts",
      marketValue: "$2.5 per pound",
      image: "https://www.health.com/thmb/v0b1-O1_M5D60QgSf1c8CaPradA=/2163x0/filters:no_upscale():max_bytes(150000):strip_icc()/Kiwi-a2e9888bfab6474f8d12d2ae0287b356.jpg",
      fallbackText: "Kiwi - Small, green fruit with a tangy taste, used in desserts and salads.",
    },
    {
      name: "Papaya",
      region: "Tropics",
      uses: "Eating raw, smoothies",
      marketValue: "$1.5 per pound",
      image: "https://www.stroke.org/-/media/Images/News/2023/October-2023/1013EIOLIPapaya_SC.jpg",
      fallbackText: "Papaya - Tropical fruit known for its sweet flavor and use in smoothies.",
    },
    {
      name: "Tangrine",
      region: "Mediterranean",
      uses: "Juice, cooking, desserts",
      marketValue: "$2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFj7OlBMLXdX35kGTNomifK7XRny2Hvkcb9g&s",
      fallbackText: "Lemon - Citrus fruit used for its tangy juice and zest in cooking and desserts.",
    },
    {
      name: "Plum",
      region: "Worldwide",
      uses: "Eating raw, jams, desserts",
      marketValue: "$2 per pound",
      image: "https://exoticflora.in/cdn/shop/products/santa-rosa-plum-tree-2.wdp.jpg?v=1499122116",
      fallbackText: "Plum - Sweet and tart fruit enjoyed raw or in jams and desserts.",
    },
    {
      name: "Cherry",
      region: "Europe, Asia, North America",
      uses: "Eating raw, desserts",
      marketValue: "$4 per pound",
      image: "https://m.media-amazon.com/images/I/618flJ0XILL._AC_UF1000,1000_QL80_.jpg",
      fallbackText: "Cherry - Juicy fruit used in desserts and enjoyed fresh.",
    },
    {
      name: "Pear",
      region: "Europe, Asia",
      uses: "Eating raw, cooking, desserts",
      marketValue: "$2.5 per pound",
      image: "https://www.health.com/thmb/lE6czhltdK7OsnjWv8QcsveJxkI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/pears-9be62bfe42d14047a59efc9f7cde6023.jpg",
      fallbackText: "Pear - Sweet fruit used in cooking and desserts.",
    },
    {
      name: "Coconut",
      region: "Tropics",
      uses: "Oil, water, cooking",
      marketValue: "$1.2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPzIl_e9MnWFWZ5vqG-ozRrPoI9DpIT-ozaQ&s",
      fallbackText: "Coconut - Versatile fruit used for its water, oil, and meat.",
    },
    {
      name: "Fig",
      region: "Mediterranean",
      uses: "Eating raw, desserts, cooking",
      marketValue: "$3 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStA1M2qGrK3mYDfxjPyc76FQEiUFLjbZeTDg&s",
      fallbackText: "Fig - Sweet fruit used in desserts and cooking.",
    },
    {
      name: "Avocado",
      region: "Central America, South America",
      uses: "Guacamole, salads, smoothies",
      marketValue: "$2.5 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkj6oIVQFL-AhAM-4h7mtYodNvZ4kJW9VYPA&s",
      fallbackText: "Avocado - Creamy fruit used in guacamole, salads, and smoothies.",
    },
    {
      name: "Blueberry",
      region: "North America",
      uses: "Eating raw, desserts, smoothies",
      marketValue: "$5 per pound",
      image: "https://i0.wp.com/images-prod.healthline.com/hlcmsresource/images/AN_images/blueberries-1296x728-feature.jpg?w=1155&h=1528",
      fallbackText: "Blueberry - Small, sweet fruit used in desserts and smoothies.",
    },
    {
      name: "Raspberry",
      region: "North America, Europe",
      uses: "Eating raw, desserts, jams",
      marketValue: "$6 per pound",
      image: "https://rukminim2.flixcart.com/image/850/1000/j77xjm80/plant-seed/j/z/r/10-raspberry-fruit-ready-to-sow-national-gardens-original-imaexgcgtqpgmyzg.jpeg?q=90&crop=false",
      fallbackText: "Raspberry - Tart fruit used in desserts and jams.",
    },
    {
      name: "Blackberry",
      region: "North America, Europe",
      uses: "Eating raw, jams, desserts",
      marketValue: "$5 per pound",
      image: "https://www.starkbros.com/images/dynamic/7463.jpg",
      fallbackText: "Blackberry - Juicy fruit used in jams and desserts.",
    },
    {
      name: "Date",
      region: "Middle East, North Africa",
      uses: "Eating raw, desserts, cooking",
      marketValue: "$6 per pound",
      image: "https://assets.vogue.in/photos/5ce414714a30b36c5712b3e1/2:3/w_2560%2Cc_limit/dates-for-skincare-hair-health-weight-loss.jpg",
      fallbackText: "Date - Sweet fruit used in desserts and as a snack.",
    },
    {
      name: "Grapefruit",
      region: "Tropics",
      uses: "Juice, eating raw",
      marketValue: "$3 per pound",
      image: "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Fresh-Organic-Pink-Grapefruit-with-Mint.jpg",
      fallbackText: "Grapefruit - Bitter-sweet citrus fruit used for juice and eating raw.",
    },
    {
      name: "Apricot",
      region: "Asia, Europe",
      uses: "Eating raw, desserts, jams",
      marketValue: "$4 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnjM1ETgzDUvhkJYjgz3nC1nLd5op2qrHPFg&s",
      fallbackText: "Apricot - Sweet fruit used in jams and desserts.",
    },
    {
      name: "Lemon",
      region: "Asia, Europe",
      uses: "Eating raw, juice",
      marketValue: "$2 per pound",
      image: "https://cdn.britannica.com/84/188484-050-F27B0049/lemons-tree.jpg",
      fallbackText: "Tangerine - Citrus fruit used for its sweet segments and juice.",
    },
    {
      name: "Pineberry",
      region: "South America",
      uses: "Eating raw, desserts",
      marketValue: "$7 per pound",
      image: "https://media.istockphoto.com/id/1366067370/photo/pineberry-or-white-strawberry-on-wooden-plate-with-dark-background.jpg?s=612x612&w=0&k=20&c=OCTVRmoPzR_n69kIOaMfE1LEyol_AAQKPI3CI6LHwls=",
      fallbackText: "Pineberry - White strawberry with a pineapple flavor.",
    },
    {
      name: "Jackfruit",
      region: "Tropics",
      uses: "Eating raw, cooking",
      marketValue: "$1.5 per pound",
      image: "https://hips.hearstapps.com/hmg-prod/images/full-frame-shot-of-jackfruits-for-sale-at-market-royalty-free-image-1579270980.jpg",
      fallbackText: "Jackfruit - Large fruit with a sweet taste, used in cooking and raw.",
    },
    {
      name: "Durian",
      region: "Southeast Asia",
      uses: "Eating raw, desserts",
      marketValue: "$5 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdR9iOM4rsB0C3iWqRKFa4CYe_niOYbtauLw&s",
      fallbackText: "Durian - Unique fruit known for its strong odor and rich flavor.",
    },
    {
      name: "Starfruit",
      region: "Tropics",
      uses: "Eating raw, salads",
      marketValue: "$4 per pound",
      image: "https://healthiersteps.com/wp-content/uploads/2021/03/starfruit-ripe.jpg",
      fallbackText: "Starfruit - Tropical fruit with a star-like shape and tangy flavor.",
    },
    {
      name: "Guava",
      region: "Tropics",
      uses: "Eating raw, juice",
      marketValue: "$3 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpJbTzS1CcxDa7G_OYzWH0TUJBF1M81R7R7w&s",
      fallbackText: "Guava - Sweet fruit used in juices and eaten raw.",
    },
    {
      name: "Rhubarb",
      region: "Europe, Asia",
      uses: "Cooking, desserts",
      marketValue: "$4 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl0tTAD5ZfFT4z1URKnh-N1al464kz5PVDCg&s",
      fallbackText: "Rhubarb - Tart vegetable often used in desserts and cooking.",
    },
    {
      name: "Cantaloupe",
      region: "Tropics",
      uses: "Eating raw, smoothies",
      marketValue: "$2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1rF4cq_q4hty8gtLWtoQ37LjTctQryAR13w&s",
      fallbackText: "Cantaloupe - Sweet melon used in raw eating and smoothies.",
    },
    {
      name: "Honeydew",
      region: "Tropics",
      uses: "Eating raw, desserts",
      marketValue: "$2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBP39tsiYQ2mu3gb5gudsUh1ADPgnNE2YZhA&s",
      fallbackText: "Honeydew - Sweet melon used in desserts and raw eating.",
    },
    {
      name: "Dragon Fruit",
      region: "Mexico, Central America",
      uses: "Eating raw, smoothies",
      marketValue: "$6 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW5ARcwJE45QWOE_FKT3yJGaVWBw7DvKI1jA&s",
      fallbackText: "Dragon Fruit - Exotic fruit known for its vibrant color and sweet taste.",
    },
    {
      name: "Mulberry",
      region: "Asia, North America",
      uses: "Eating raw, jams",
      marketValue: "$5 per pound",
      image: "https://m.media-amazon.com/images/I/51D+rZ0b0eL._AC_UF1000,1000_QL80_.jpg",
      fallbackText: "Mulberry - Sweet fruit used in jams and enjoyed raw.",
    },
    {
      name: "Lime",
      region: "Tropics",
      uses: "Juice, cooking, cocktails",
      marketValue: "$2 per pound",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTC2oQdPYRfCelA6q1c00ROVZIkKmxulnzWA&s",
      fallbackText: "Lime - Tangy citrus fruit used in juices, cooking, and cocktails.",
    },
    {
      name: "Pawpaw",
      region: "North America",
      uses: "Eating raw, smoothies",
      marketValue: "$4 per pound",
      image: "https://static01.nyt.com/images/2020/10/21/dining/21pawpaw7/21pawpaw7-mediumSquareAt3X.jpg",
      fallbackText: "Pawpaw - Tropical fruit with a custard-like texture and sweet flavor.",
    },
    {
      name: "Soursop",
      region: "Tropics",
      uses: "Juice, desserts",
      marketValue: "$5 per pound",
      image: "https://m.media-amazon.com/images/I/61YwY2-HWvL._AC_UF1000,1000_QL80_.jpg",
      fallbackText: "Soursop - Exotic fruit used for its tangy juice and in desserts.",
    },
    {
      name: "Sapotta",
      region: "Tropics",
      uses: "Juice, desserts",
      marketValue: "$5 per pound",
      image: "https://nurserylive.com/cdn/shop/products/nurserylive-chikoo-sapota-chiku-fruit-grafted-plant.jpg?v=1634215991",
      fallbackText: "Soursop - Exotic fruit used for its tangy juice and in desserts.",
    },
  ];
const AboutFruit = () => {
  return (
    <div className="fruit-container">
      {fruitsData.map((fruit, index) => (
        <div key={index} className="fruit-card">
          <img
            src={fruit.image}
            alt={fruit.name}
            onError={(e) => e.target.alt = fruit.fallbackText}
            className="fruit-image"
          />
          <h2 className="fruit-name">{fruit.name}</h2>
          <p className="fruit-region"><strong>Mostly Found In:</strong> {fruit.region}</p>
          <p className="fruit-uses"><strong>Uses:</strong> {fruit.uses}</p>
          <p className="fruit-value"><strong>Market Value:</strong> {fruit.marketValue}</p>
        </div>
      ))}
    </div>
  );
};

export default AboutFruit;
